### ISSUE TITLE
uvloop.__version__ isn't set

### ISSUE THREAD

**Issue by MarkReedZ** [MagicStack/uvloop#137]
\_\_init__.py should set the version though the following can be done to get the version:

```
import pkg_resources
pkg_resources.require("uvloop")[0].version
```

**Comment by kxepal** [comment]
Not really. pkg_resources gets all the information from package metainformation (`.egg-info` or `.dist-info`). If you install uvloop correctly (via pip), then it will works as expected.
```
$ pip install uvloop
Collecting uvloop
  Downloading uvloop-0.9.1-cp36-cp36m-manylinux1_x86_64.whl (3.2MB)
    100% |████████████████████████████████| 3.2MB 451kB/s 
Installing collected packages: uvloop
Successfully installed uvloop-0.9.1
$ python
Python 3.6.5 (default, Apr  8 2018, 11:23:52) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.require("uvloop")[0].version
'0.9.1'
>>> type(pkg_resources.require("uvloop")[0])
<class 'pkg_resources.DistInfoDistribution'>
>>> 
```

**Comment by MarkReedZ** [comment]
I may have worded that wrong, but python states you should make the version number available in __version__ which I don't think is set by uvloop.

**Comment by asvetlov** [comment]
IMHO Python never *states* it.
But very many distros (not all) have `__version__` attribute in top level package.

**Comment by kxepal** [comment]
`__version__` thing is just an agreement the same as `__author__`, `__revision__` and the rest of those. These has no effect nor special meaning. However, version in package metadata matters since all the managers (pip, setuptools, pipenv) will use it for their work. Which makes it's more reliable source of truth than some custom module attribute.

The main problem with `__version__` attribute is a chicken and egg one. You need package version to install the package, but you can't get package version without install it. So you have to found yourself to do import hacks (install-without-install) or doing regexp parsing. Not quite cool nor reliable ways to go just to achieve...what?

**Comment by 1st1** [comment]
What's the actual intent behind checking `__version__`? Ideally you should never depend on it in your source code.

**Comment by sakurai-youhei** [comment]
FYI: Mine is reliable & straightfoward version check by `python -c 'import uvloop; print(uvloop.__version__)'` rather than querying pip.
