### ISSUE TITLE
japronto breaks with uvloop. Is this a japronto or uvloop issue?

### ISSUE THREAD

**Issue by btegs** [MagicStack/uvloop#140]
My original issue is at https://github.com/squeaky-pl/japronto/issues/122 and I'm not sure if its the recent version of uvloop causing an error or the fact that japronto hasn't been maintained in a while. Uvloop works fine with Sanic, but japronto errors out on basic page load.

**Comment by 1st1** [comment]
Can you attach the full script to reproduce, along with versions of dependencies that you used?

**Comment by btegs** [comment]
I'll give it a go again when I get home, but I did revert to uvloop 0.8.1 and it ran without a hitch.

**Comment by squeaky-pl** [comment]
This doesn't belong here. The problem probably lies in Japronto: The original issue is here https://github.com/squeaky-pl/japronto/issues/99

**Comment by squeaky-pl** [comment]
I hinted the issue author what he needs to do to fix it in https://github.com/squeaky-pl/japronto/issues/122, feel free to close.

**Comment by 1st1** [comment]
Thanks, @squeaky-pl.

**Comment by btegs** [comment]
This isn't my project, so the fixing will have to come on yours or japronto's end.

**Comment by btegs** [comment]
True, but when the maintainer of this project, @squeaky-pl is saying "I hinted the issue author what he needs to do to fix it" it shows that he doesn't care about this project and it should be moved to inactive status. It works with uvloop 0.8.1 but you don't want to force people to downgrade their packages.

**Comment by squeaky-pl** [comment]
"He doesn't care" is a very broad statement. I certainly do care, if I would not care I would not bother to respond to you, or certainly not provide any further information. It's true that the project development is stale or inactive but I am not going to pull it down just because of that. I am also in touch with a couple of companies that actively keep using it (it's paid consulting, not open source). They didn't have a problem with uvloop version so far.

Anyway now with the steps hopefully somebody with spare open-source time can provide a fix before I get into it.

Please don't continue this discussion here, but in japronto repo instead.
