### ISSUE TITLE
Integration with Cython

### ISSUE THREAD

**Issue by davidbrochart** [MagicStack/uvloop#210]
When using uvloop in Cython, does it call the interpreter or does it remain on the Cython side?

**Comment by 1st1** [comment]
There's no "Cython side"; Cython compiles itself to C that calls into CPython C API. uvloop is all in Cython, so its own code isn't being interpreted.  But whenever a callback written in pure Python is scheduled it's executed with CPython ceval loop (the interpreter).

**Comment by 1st1** [comment]
Feel free to ask more questions!

**Comment by davidbrochart** [comment]
Thanks @1st1. To be more precise, I want to write some Cython code that will use asyncio. If I replace asyncio with uvloop, is it going to involve the CPython interpreter at all (and will that be a big penalty), or is it going to be Cython calling Cython?

**Comment by 1st1** [comment]
Cython-generated code always involves CPython code.  Roughly speaking, for a program compiled with Cython, roughly all of CPython core code is executed. It's just that instead of CPython opcode evaluator calling C API, the generated C code calls it.  When you compile a pure Python code snippet like

```python
print('a')
```

instead of evaluating `CALL_FUNCTION` opcode that calls Python's `print()` implementation, Cython will compile C code that calls Python's `print()` implementation.  The goal here is to make sure that all performance-critical parts are compiled with Cython and avoid the slow path of CPython's opcode interpreter.  In other words, it's not possible to not involve CPython interpreter completely, and it shouldn't even be a goal.
