### ISSUE TITLE
uvloop alpha release

### ISSUE THREAD

**Issue by 1st1** [MagicStack/uvloop#3]
Some ToDo items we need completed before we make an alpha release:

- [x] Implement `loop.create_connection`
- [x] Add few more tests for `loop.create_server` to increase the coverage
- [x] Add a few high-level tests involving aiohttp or another real codebase
- [x] Implement `loop.create_unix_server`
- [x] Implement `loop.create_unix_connection`
- [x] Implement `loop.subprocess_shell` and `loop.subprocess_exec`
- [x] Implement `loop.getnameinfo`
- [x] Implement `loop.add_signal_handler` and `loop.remove_signal_handler`
- [x] Implement `loop.connect_read_pipe` and `loop.connect_write_pipe`
- [x] Implement SSL
- [x] Implement `loop.create_datagram_endpoint`

**Comment by 1st1** [comment]
Added basic `loop.create_unix_server` in b1c130b80a986ffaa9ea49bce5c42d474b36753b

**Comment by 1st1** [comment]
Added tests for `loop.create_unix_server` in c93da26c35607518f286dbdf9023034288074fab

**Comment by 1st1** [comment]
Added support for `sock` parameter to `loop.create_unix_server` in 55228cb6adcf051d01f64d966b31dcbf61479397

**Comment by 1st1** [comment]
Added basic implementation of `loop.create_connection` in e6f1d45135b7dab0510410dd89761cbe8eecca46 and a6266752babe6b826fa4a5e368d50de0dd6063f9.

TODO: Add tests.

**Comment by 1st1** [comment]
Added basic implementation of `subprocess*` functions in 800cde0d9a062a7e1af3bcb6bb90b6f7f8f44432

**Comment by 1st1** [comment]
Implemented `loop.connect_read_pipe` and `loop.connect_write_pipe` in e293b283f8db181d9c9be580806b6560043a4067

**Comment by 1st1** [comment]
`loop.subprocess_shell` and `loop.subprocess_exec` are almost done (see 1f4e720c229ed5eaa13f2aade5c7a401ea7ab7ed, 704eb6fa08d63cd55fcf6fc3e028d361e0f028e4, 5bcb103a9adc9200b597f2c847fe850db5185990, and 28d166e19342ab151280fa7d73c7101f0ef28cd7)

**Comment by 1st1** [comment]
`loop.subprocess_shell` and `loop.subprocess_exec` are done now (see 91d17cdb394ee17ba1fcff8dba9cd3dee9171d98 and b8c410a646e5d9d0be8ac5be51d8b131c4f0ef6b)

**Comment by 1st1** [comment]
Solved bunch of small issues and implemented `create_unix_connection` in 203a181bcab56e211de27d724d2cfe4ac56331e1

**Comment by 1st1** [comment]
`loop.getnameinfo` has landed in 4b9471279321133e648abfb5bf40521fe22da687

**Comment by 1st1** [comment]
5457d1eda3af9831882a9d14663ab15e5ee76e35 implements `loop.add_signal_handler` and `loop.remove_signal_handler`

**Comment by 1st1** [comment]
SSL landed in 2ed225eff9fd7e41bc34c6fe1a99a8b48cb3ce44 and 494894701e9b3d140a875d46325bb680f07b8ad5

**Comment by 1st1** [comment]
UDP landed in deff28dc5ea1b9fe63809b9f65183b588c812696

**Comment by 1st1** [comment]
Almost there. Will release an alpha version officially in a day or two. /cc @sametmax @asvetlov

**Comment by 1st1** [comment]
Done! http://magic.io/blog/uvloop-make-python-networking-great-again/

**Comment by sametmax** [comment]
All tests pass on my machine (Ubuntu 14.04, Python 3.5 64b):

```
$ make test
PYTHONASYNCIODEBUG=1 python -m unittest discover -s tests
............................................................................................................................................................................
----------------------------------------------------------------------
Ran 172 tests in 34.116s

OK
python -m unittest discover -s tests
............................................................................................................................................................................
----------------------------------------------------------------------
Ran 172 tests in 24.181s

OK
```

It's really, really sweet. 

I have a project using asyncio, and most unit tests are passing with uvloop too.

Currently the tests not passing are linked to the way we customize error handling. Errors like "AttributeError: '_Loop' object has no attribute '_exception_handler'". 

On one hand, we kinda deserve it, since we are clearly access a private attribute. On the other hand, the way asyncio handles errors really need some customization to be usable, so we wrap it into a coherent API, and it breaks with uvloop. I'm wondering if we should detect uvloop running, and handle errors differently with it. But that would need create a whole separate code for handling sigterm, a fail fast debug mode, etc.

**Comment by 1st1** [comment]
@sametmax I guess I can make `_exception_handler` available as a read-only property. Would that work for you?

**Comment by sametmax** [comment]
It would help us with this issue, since to set the exception handler we use the public set_exception_handler(), but there is not such thing as get_exception_handler in asyncio's API.

But maybe that's the wrong road. Maybe I should open a ticket to get get_exeption_handler added to the API, the you go add this official API as well instead of copying something that is meant to be internal.

All in all, our project is not a big deal to anybody yet, so I don't want to make you feel like you need to spend time on this unless some other projects have a similar issue. I'm just raising it so that you can increment the counter in your head of people reporting the problem :)

**Comment by 1st1** [comment]
> But maybe that's the wrong road. Maybe I should open a ticket to get get_exeption_handler added to the API, the you go add this official API as well instead of copying something that is meant to be internal.

This is a very good idea. I suggest you to go ahead and open an issue on http://github.com/python/asyncio. Most of the "set_*" APIs have a corresponding "get_" method, so I see no problem in adding one more, provided that you have a use case.  You'll see it in Python 3.5.2.
