### ISSUE TITLE
Pip doesn’t install wheels

### ISSUE THREAD

**Issue by rlippmann** [MagicStack/uvloop#542]
* **uvloop version**: 0.17
* **Python version**: 3.10.6
* **Platform**: Ubuntu 22.04/Alpine 3.17
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:
* **Does uvloop behave differently from vanilla asyncio? How?**:

This is more a question than an issue. When I install uvloop via pip, it drags in cython/gcc and builds rather than using wheels. On alpine/docker I wind up getting a glibc library instead of musl.  Which still works, but…

Is this intended functionality?

**Comment by ben9923** [comment]
`uvloop` 0.17.0 has `musllinux` wheels available on PyPI.
Are you still getting a sdist rather than a wheel? Are you using a recent enough `pip`?

Checking both `alpine:3.17` and `python:alpine3.17` resulted in a wheel being used for me:
```shell
docker run --rm -it --init alpine:3.17
apk add python3 py3-pip
pip install uvloop
```

```shell
docker run --rm -it --init python:3.10-alpine3.17 sh
pip install uvloop
```

Can you share the `pip install` output? Preferably a verbose one? :)

**Comment by rlippmann** [comment]
Sorry for the delay.

I can't reproduce it either in docker or in a virtualenv in Ubuntu, so I'm closing
